# .github/release-drafter.yml
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Performance'
    labels:
      - 'performance'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'refactor'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'Security'
    labels:
      - 'security'
  - title: 'Testing'
    labels:
      - 'test'
      - 'testing'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
  default: patch

exclude-labels:
  - 'skip-changelog'
  - 'dependencies'

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**/*'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'refactor'
    branch:
      - '/refactor\/.+/'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION